
# Print debugging to a debug logfile
debug = false
# Debug logfile (default debugfile is timestamped)
debugfile = 'tuatara.log'

[art]
# What art fetchers to use
fetchers = ['apple', 'musicbrainz']
# Whether to automatically set background color to match track art
dynamic_background = true
# Ratio of terminal font height to width
font_ratio = 2.0
# Pre-ascii-ify art image adjustments
brightness_adj = 0.75
contrast_adj = 1.25
# Visualization plugin. Set to 'none' to disable visualization.
visualization = 'synaescope'
