
# Print debugging to stderr
debug = false
# Debug file (default debugfile is timestamped)
debugfile = 'tuatara.log'

[art]
# What art fetchers to use
fetchers = ['apple', 'musicbrainz']
# Ratio of terminal font height to width
font_ratio = 2.0
# libcaca dithering algorithm
dither = 'fstein'
# libcaca charset
charset = 'ascii'
# Pre-caca art image adjustments
brightness_adj = 0.75
contrast_adj = 1.25
# Visualizartion plugin
visualization = 'synaescope'
