name: "Release"

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install system build deps
      run: |
        sudo apt install libgirepository-2.0-dev gir1.2-gstreamer-1.0 libcairo2-dev gir1.2-gdkpixbuf-2.0
    - name: Install runtime tools
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Setup poetry env
      run: |
        poetry install
    - name: Build package
      run: |
        SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) \
        poetry build
        cd dist && for file in * ; do sha256sum $file > $file.sha256sum ; done

    - name: "Upload dists"
      uses: "actions/upload-artifact@v4"
      with:
        name: "release"
        path: "dist/"
        if-no-files-found: error
        retention-days: 1

  publish:
    name: "Publish"
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build"]
    environment: pypi
    permissions:
      contents: write
      id-token: write
    runs-on: "ubuntu-latest"

    steps:
    - name: "Download dists"
      uses: actions/download-artifact@v4
      with:
        name: "release"
        path: "dist/"

    - name: "Upload dists to GitHub Release"
      env:
        GITHUB_TOKEN: "${{ secrets.PUBLISH_KEY }}"
      run: |
        gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}

    - name: "Remove shasums before PyPI publish"
      run: |
        rm -f dist/*.sha256sum

    - name: "Publish dists to PyPI"
      uses: pypa/gh-action-pypi-publish@release/v1
